--Insert de estudiantes
INSERT INTO estudiantes (nombre, carrera, correo) VALUES
('Ana Martínez', 'Ingeniería en Sistemas', 'ana.martinez01@universidad.edu'),
('Luis Gómez', 'Administración de Empresas', 'luis.gomez02@universidad.edu'),
('Carla Rodríguez', 'Psicología', 'carla.rodriguez03@universidad.edu'),
('Pedro López', 'Derecho', 'pedro.lopez04@universidad.edu'),
('María Hernández', 'Medicina', 'maria.hernandez05@universidad.edu'),
('Carlos Méndez', 'Arquitectura', 'carlos.mendez06@universidad.edu'),
('Sofía Pérez', 'Ingeniería Civil', 'sofia.perez07@universidad.edu'),
('Jorge Castillo', 'Contaduría Pública', 'jorge.castillo08@universidad.edu'),
('Lucía Morales', 'Diseño Gráfico', 'lucia.morales09@universidad.edu'),
('Miguel Torres', 'Ingeniería Eléctrica', 'miguel.torres10@universidad.edu'),
('Daniela Ruiz', 'Biología', 'daniela.ruiz11@universidad.edu'),
('Andrés Vargas', 'Economía', 'andres.vargas12@universidad.edu'),
('Camila Navarro', 'Química', 'camila.navarro13@universidad.edu'),
('Juan Pablo Díaz', 'Historia', 'juanp.diaz14@universidad.edu'),
('Valeria Soto', 'Sociología', 'valeria.soto15@universidad.edu'),
('Esteban Aguilar', 'Ingeniería Mecánica', 'esteban.aguilar16@universidad.edu'),
('Paula Jiménez', 'Filosofía', 'paula.jimenez17@universidad.edu'),
('Ricardo Salazar', 'Computación', 'ricardo.salazar18@universidad.edu'),
('Natalia Rivas', 'Periodismo', 'natalia.rivas19@universidad.edu'),
('Francisco Cordero', 'Ingeniería Química', 'francisco.cordero20@universidad.edu'),
('Gabriela Ramos', 'Relaciones Internacionales', 'gabriela.ramos21@universidad.edu'),
('Diego Cabrera', 'Educación', 'diego.cabrera22@universidad.edu'),
('Alejandra León', 'Trabajo Social', 'alejandra.leon23@universidad.edu'),
('Tomás Pineda', 'Ingeniería Industrial', 'tomas.pineda24@universidad.edu'),
('Isabella Cruz', 'Marketing', 'isabella.cruz25@universidad.edu'),
('Sebastián Molina', 'Nutrición', 'sebastian.molina26@universidad.edu'),
('Mónica Estrada', 'Veterinaria', 'monica.estrada27@universidad.edu'),
('Felipe Ramírez', 'Matemática', 'felipe.ramirez28@universidad.edu'),
('Renata Fuentes', 'Antropología', 'renata.fuentes29@universidad.edu'),
('Cristóbal Silva', 'Ingeniería en Telecomunicaciones', 'cristobal.silva30@universidad.edu');


--insert de clubs
INSERT INTO clubes (nombre, tipo) VALUES
('Club de Robótica', 'Académico'),
('Club de Debate', 'Académico'),
('Club de Teatro', 'Cultural'),
('Club de Ajedrez', 'Académico'),
('Club de Música', 'Cultural'),
('Club de Fotografía', 'Cultural'),
('Club de Atletismo', 'Deportivo'),
('Club de Lectura', 'Cultural'),
('Club de Programación', 'Tecnológico'),
('Club de Cine', 'Cultural'),
('Club de Voluntariado', 'Social'),
('Club de Emprendimiento', 'Académico'),
('Club de Coro', 'Académico'),
('Club de Danza', 'Cultural'),
('Club de Boxeo', 'Deportivo');

-- tabla de unión 
INSERT INTO clubes_estudiantes (id_club, id_estudiante, actividad, cargo) VALUES
(1, 1, 'activo', 'presidente'),
(1, 2, 'activo', 'miembro'),
(1, 3, 'activo', 'vocal'),
(2, 4, 'inactivo', 'miembro'),
(2, 5, 'activo', 'presidente'),
(2, 6, 'activo', 'vocal'),
(3, 7, 'activo', 'presidente'),
(3, 8, 'vetado', 'miembro'),
(3, 9, 'activo', 'tesorero'),
(4, 10, 'activo', 'presidente'),
(4, 11, 'activo', 'miembro'),
(4, 12, 'activo', 'vocal'),
(5, 13, 'inactivo', 'miembro'),
(5, 14, 'activo', 'presidente'),
(5, 15, 'activo', 'vicepresidente'),
(6, 16, 'activo', 'tesorero'),
(6, 17, 'activo', 'miembro'),
(6, 18, 'vetado', 'miembro'),
(7, 19, 'activo', 'presidente'),
(7, 20, 'activo', 'vocal'),
(7, 21, 'activo', 'miembro'),
(8, 22, 'inactivo', 'tesorero'),
(8, 23, 'activo', 'presidente'),
(8, 24, 'activo', 'miembro'),
(9, 25, 'activo', 'presidente'),
(9, 26, 'activo', 'vicepresidente'),
(9, 27, 'activo', 'miembro'),
(10, 28, 'activo', 'vocal'),
(10, 29, 'inactivo', 'miembro'),
(10, 30, 'activo', 'tesorero'),
(11, 1, 'activo', 'miembro'),
(11, 3, 'activo', 'vocal'),
(11, 5, 'vetado', 'miembro'),
(12, 7, 'activo', 'presidente'),
(12, 9, 'activo', 'tesorero'),
(12, 11, 'inactivo', 'miembro'),
(13, 13, 'activo', 'miembro'),
(13, 15, 'activo', 'vicepresidente'),
(13, 17, 'activo', 'vocal'),
(14, 19, 'activo', 'presidente'),
(14, 21, 'activo', 'tesorero'),
(14, 23, 'activo', 'miembro'),
(15, 25, 'activo', 'presidente'),
(15, 27, 'vetado', 'miembro'),
(15, 29, 'activo', 'miembro');
