services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5430:5432"
    volumes:
      - ./database/init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql  
      # - ./02-data.sql:/docker-entrypoint-initdb.d/02-data.sql
  

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://myuser:mypass@db:5432/mydb
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"